first_project/urls.py
from django.contrib import admin
from django.urls import path
from firstapp import views
from django.urls import include

urlpatterns = [
    path('',views.index,name='index'),
    path('',include('firstapp.urls')),
    path('admin/', admin.site.urls),
]

firstapp/urls.py
from django.urls import path,re_path
from firstapp import views


app_name='firstapp'

urlpatterns=[
    path('firstapp',views.index,name='index'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.blog_detail,name=' blog_detail'),
    path('signup/',views.signup_view,name="signup"),
    path('new/',views.user_account,name="new"),

]

firstapp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(default='')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    def snippest(self):
        return self.text[:20]+"...."
        
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254,unique=True)

firstapp/forms.py
from django import forms
from firstapp.models import User

class form_view(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    text=forms.CharField(widget=forms.Textarea)
    
class NewUserform(forms.ModelForm):
    class Meta:
        model=User
        fields='__all__'

firstapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from firstapp.models import Post,User
from firstapp.forms import NewUserform,form_view

def index(request):
    posts=Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    my_dict={'posts':posts}
    return render(request,'firstapp/index.html',context= my_dict)

def blog_detail(request,slug):
    # return HttpResponse(slug)
    blog=Post.objects.get(slug=slug)
    return render(request,'article_detail.html',{'blogs':blog})

def signup_view(request):
    form=form_view()
    if request.method =='POST':
        form=form_view(request.POST)
        if form.is_valid():
            #do something here
            print("validation success")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])
    return render(request,"signup.html",{'form':form})

def user_account(request):
    form=NewUserform()
    if request.method =='POST':
        form=NewUserform(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("error/....")
    return render(request,'user.html',{'form':form})


# Create your views here.

templates/article_detail.html
{%extends 'base.html'%}

{%block content%}
<div class="article-detail">
  <div class="article">
    <h2>{{blogs.title}}</h2>
      <p>Published:{{blogs.published_date}}</p>
      <p>{{blogs.text|linebreaksbr}}</p>
  </div>

</div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>first app</title>
     <link rel="stylesheet" href="{%static "css/my.css"%}">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <body>
    <div class="wrapper">
      <h1><a href="{%url 'firstapp:index'%}">Akshay's Blog</a></h1>
      {% block content %}

      {% endblock %}

    </div>
  </body>
</html>

templates/index.html
{%extends 'base.html'%}

{%block content%}
<div class="container">
      <!-- <h1>Akshay's Blog</h1> -->
    {%for post in posts%}

      <h2><a href="{% url 'detail' slug=post.slug %}">{{ post.title }}</a></h2>
      <p id="para1">Published:{{post.published_date}}</p>
      <p id="para2">{{post.snippest|linebreaksbr}}</p>
      <p><a href="{%url 'firstapp:signup'%}">sign up page</a></p>
    {% endfor %}
</div>
{%endblock%}

templates/signup.html
{%extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h3 id="head3">Please fill the form</h3>
  </div>

</div>

<div class="container">
  <form  method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="save">
  </form>



</div>

{% endblock %}

templates/user.html
{%extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h3 id="head3">Please SignUp!!</h3>
  </div>

</div>

<div class="container">
  <form  method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="save">
  </form>
</div>

{% endblock %}